name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: sgccr.ccs.tencentyun.com
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sgccr.ccs.tencentyun.com/mousegaze/mouse-gaze:latest
    # - name: Install SSH client
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y openssh-client
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
    # - name: Deploy to Server
    #   run: |
    #     ssh ubuntu@${{ secrets.IP }} << 'EOF'
    #     sudo docker stop rats mouse || true
    #     sudo docker rm rats mouse || true
    #     sudo docker pull evilharry1024/mouse-gaze:latest
    #     sudo docker run --name rats --network=rats-net -d -p 8002:8000 -v /home/ubuntu/mousegaze/conf/config.ini:/app/conf/config.ini evilharry1024/mouse-gaze uvicorn cmd.rats.rats:app --host 0.0.0.0 --port 8000
    #     sudo docker run --name mouse --network=rats-net -d -p 8001:8000 -v /home/ubuntu/mousegaze/resource:/app/resource evilharry1024/mouse-gaze uvicorn cmd.mouse.mouse:app --host 0.0.0.0 --port 8000
    #     EOF